
export const config = {
  root_nick: 'bLueStar',
  script_name: 'PAPATYA',
  script_version: 'v7',
  server_name: 'SiberTR IRC Network',
  server: 'irc.sibertr.net',
}

export const bar = [
  { menu: 'File', submenu: ['New', 'Open', 'Save'] },
  { menu: 'View', submenu: ['Zoom In', 'Zoom Out'] },
  { menu: 'Favorites', submenu: ['Add to Favorites', 'View Favorites'] },
  { menu: 'Tools', submenu: ['Options', 'Settings'] },
  { menu: 'PAPATYA Script v7 e-mIRC', submenu: ['About', 'Help'] },
  { menu: 'Window', submenu: ['Minimize', 'Maximize'] },
  { menu: 'Help', submenu: ['Documentation', 'Support'] },
];

export const DEFAULT_CHANNELS = ['str_chat', 'PAPATYA', 'WebCam', 'Radyo', 'mIRCHane'];

export const opPriority: Record<string, number> = {
  "~": 1,
  "&": 2,
  "@": 3,
  "%": 4,
  "+": 5,
  "": 6,
};

export const op_colors = [
  { sign: "~", color: "green" },
  { sign: "&", color: "#74140c" },
  { sign: "@", color: "#ea3323" },
  { sign: "%", color: "#00007a" },
  { sign: "+", color: "#0000f2" },
];

export const formatDate = (date: Date): string => {
  const days = [
    "Pazar", "Pazartesi", "Salı", "Çarşamba",
    "Perşembe", "Cuma", "Cumartesi"
  ];

  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = date.getFullYear();
  const dayName = days[date.getDay()];

  const hours = String(date.getHours()).padStart(2, "0");
  const minutes = String(date.getMinutes()).padStart(2, "0");
  const seconds = String(date.getSeconds()).padStart(2, "0");

  return `Tarih: ${day}/${month}/${year} ${dayName} - ${hours}:${minutes}:${seconds}`;
};

export const chats = [
  { "time": "02:07", "event": "chat", "message": "Bişeyi anlayamıyorum bile kafam hamura dönüyor", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:07", "event": "chat", "message": "Açmasan atar gider yapıyor", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:07", "event": "chat", "message": "Telefon", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:07", "event": "chat", "message": "Herşey çok çabuk eskitiliyor", "user": "Mina", "new_nick": null, "email": null, "channel": null },
  { "time": "02:08", "event": "chat", "message": "Çok çabuk değişiyor olaylar", "user": "Mina", "new_nick": null, "email": null, "channel": null },
  { "time": "02:08", "event": "quit", "message": "", "user": "ergin", "new_nick": null, "email": "PAPATYAv7@5E.79.3D55634C.sibertr.net", "channel": null },
  { "time": "02:08", "event": "nick_change", "message": "", "user": "Hazal", "new_nick": "Hazal' Away", "email": null, "channel": null },
  { "time": "02:08", "event": "chat", "message": "Maksatta bu belki", "user": "Mina", "new_nick": null, "email": null, "channel": null },
  { "time": "02:08", "event": "chat", "message": "Kafaların karışması", "user": "Mina", "new_nick": null, "email": null, "channel": null },
  { "time": "02:08", "event": "chat", "message": "yazmık ettiler bizim gibilerine senin gibilerine", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:08", "event": "login", "message": "", "user": "PAPATYA-v7-292", "new_nick": null, "email": "PAPATYAv7@5F.5A0E9A1C5.sibertr.net", "channel": "#str_chat" },
  { "time": "02:09", "event": "chat", "message": "Hiç durma aynı adamla telefon görüşmesi yapılır mı", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:09", "event": "chat", "message": "Nasıl :)))))", "user": "Mina", "new_nick": null, "email": null, "channel": null },
  { "time": "02:09", "event": "chat", "message": "Telefon rehberinde yaklaşık 400 tane adam var 1000 de 1000'i aynı adam aramakta", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:09", "event": "login", "message": "", "user": "sevde", "new_nick": null, "email": "PAPATYAv7@D9.52.952D5224.sibertr.net", "channel": "#str_chat" },
  { "time": "02:09", "event": "login", "message": "", "user": "aysunn", "new_nick": null, "email": "TurkishM@25.C9.8974D62C.sibertr.net", "channel": "#str_chat" },
  { "time": "02:09", "event": "chat", "message": "Misal verdim de yani", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:10", "event": "chat", "message": "Yaa :)", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:10", "event": "login", "message": "", "user": "PAPATYAv7-439", "new_nick": null, "email": "PAPATYAv7@B0.DB.2F75F3CA.sibertr.net", "channel": "#str_chat" },
  { "time": "02:10", "event": "login", "message": "", "user": "Pokemon", "new_nick": null, "email": "PAPATYAv7@5.2E.21061F6E.sibertr.net", "channel": "#str_chat" },
  { "time": "02:10", "event": "chat", "message": "Anladım", "user": "Mina", "new_nick": null, "email": null, "channel": null },
  { "time": "02:10", "event": "quit", "message": "", "user": "Hazal' Away", "new_nick": null, "email": "PAPATYAv7@5.19.9B5EAEA4.sibertr.net", "channel": null },
  { "time": "02:10", "event": "chat", "message": "Bayan olsa da sesini duysan ama nerde duyamam", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:11", "event": "login", "message": "", "user": "Cokgec", "new_nick": null, "email": "PAPATYAv7@1F.8E.ECA2AA37.sibertr.net", "channel": "#str_chat" },
  { "time": "02:11", "event": "chat", "message": "Kafamızın içi yüzlerce topla dolu havada uçuşuyorlar", "user": "Mina", "new_nick": null, "email": null, "channel": null },
  { "time": "15:42", "event": "chat", "message": "Ortalık karıştı", "user": "Naren", "new_nick": null, "email": null, "channel": null },
  { "time": "15:42", "event": "chat", "message": "güzeldi", "user": "MelekSy", "new_nick": null, "email": null, "channel": null },
  { "time": "15:42", "event": "chat", "message": "Jerry ortalık aslında bi platform gibi bişi", "user": "KeeN", "new_nick": null, "email": null, "channel": null },
  { "time": "15:42", "event": "chat", "message": "Gebze", "user": "Gebze", "new_nick": null, "email": null, "channel": null },
  { "time": "15:42", "event": "chat", "message": "Meleksy hg", "user": "andaloutase", "new_nick": null, "email": null, "channel": null },
  { "time": "15:42", "event": "quit", "message": "", "user": "M33_", "new_nick": null, "email": "MobilTurki@55.6A.AB90C31D.sibertr.net", "channel": null },
  { "time": "15:42", "event": "chat", "message": "Rica", "user": "andaloutase", "new_nick": null, "email": null, "channel": null },
  { "time": "15:42", "event": "chat", "message": "ozelkapat", "user": "Esme", "new_nick": null, "email": null, "channel": null },
  { "time": "15:43", "event": "quit", "message": "", "user": "Semra560", "new_nick": null, "email": "PAPATYAv7@4E.BE.4BF22D6C.sibertr.net", "channel": null },
  { "time": "15:43", "event": "login", "message": "", "user": "EBRAR", "new_nick": null, "email": "TurkishM@58.E5.3C4CDAB7.sibertr.net", "channel": "#str_chat" },
  { "time": "15:43", "event": "chat", "message": "Öğretmen bi dişi alıcam :D", "user": "KeeN", "new_nick": null, "email": null, "channel": null },
  { "time": "15:43", "event": "chat", "message": "En doğrusu bu burda", "user": "Esme", "new_nick": null, "email": null, "channel": null },
  { "time": "15:43", "event": "chat", "message": "dışı ne ya dndjdnnd", "user": "kleopatra", "new_nick": null, "email": null, "channel": null },
  { "time": "15:43", "event": "chat", "message": "Hayırın çiftleştiriyo sanki", "user": "kleopatra", "new_nick": null, "email": null, "channel": null },
  { "time": "15:44", "event": "chat", "message": "Ciloçapatat öğretmen dişi alıcam shshshs", "user": "KeeN", "new_nick": null, "email": null, "channel": null },
  { "time": "15:44", "event": "chat", "message": "sen ne anlatıyorsun", "user": "MelekSy", "new_nick": null, "email": null, "channel": null },
  { "time": "16:30", "event": "login", "message": "", "user": "Boran", "new_nick": null, "email": "PAPATYAv7@3A.8C.F7B22134.sibertr.net", "channel": "#str_chat" },
  { "time": "16:30", "event": "chat", "message": "Selam millet, neler dönüyor?", "user": "Boran", "new_nick": null, "email": null, "channel": null },
  { "time": "16:30", "event": "chat", "message": "Hoş geldin Boran, sakin buralar.", "user": "Eylul", "new_nick": null, "email": null, "channel": null },
  { "time": "16:31", "event": "chat", "message": "Birkaç kişi vardı az önce, ama dağıldılar.", "user": "Eren_57", "new_nick": null, "email": null, "channel": null },
  { "time": "16:31", "event": "chat", "message": "Bugün çok sessiz ya, eskiden böyle değildi.", "user": "Boran", "new_nick": null, "email": null, "channel": null },
  { "time": "16:32", "event": "login", "message": "", "user": "Zehra", "new_nick": null, "email": "PAPATYAv7@5D.9F.2A3E451B.sibertr.net", "channel": "#str_chat" },
  { "time": "16:32", "event": "chat", "message": "Selam herkese!", "user": "Zehra", "new_nick": null, "email": null, "channel": null },
  { "time": "16:32", "event": "chat", "message": "Merhaba Zehra, hoş geldin.", "user": "Eylul", "new_nick": null, "email": null, "channel": null },
  { "time": "16:33", "event": "chat", "message": "Hoş bulduk, bugün neler konuştunuz?", "user": "Zehra", "new_nick": null, "email": null, "channel": null },
  { "time": "16:33", "event": "chat", "message": "Pek bi şey yok, sessizdi burası.", "user": "Eren_57", "new_nick": null, "email": null, "channel": null },
  { "time": "16:34", "event": "chat", "message": "Neyse biraz hareket getirelim. Şu an ne yapıyorsunuz?", "user": "Zehra", "new_nick": null, "email": null, "channel": null },
  { "time": "16:34", "event": "chat", "message": "Ben Netflix'e bakıyordum ama sıkıldım biraz.", "user": "Boran", "new_nick": null, "email": null, "channel": null },
  { "time": "16:35", "event": "chat", "message": "Ben de müzik dinliyorum, yeni bir playlist yaptım.", "user": "Eylul", "new_nick": null, "email": null, "channel": null },
  { "time": "16:35", "event": "quit", "message": "", "user": "Eren_57", "new_nick": null, "email": "PAPATYAv7@2B.6A.1E4D894A.sibertr.net", "channel": null },
  { "time": "16:35", "event": "chat", "message": "Eren gitti sanırım :)", "user": "Zehra", "new_nick": null, "email": null, "channel": null },
  { "time": "16:36", "event": "chat", "message": "Evet ya, sessizce kaçtı.", "user": "Eylul", "new_nick": null, "email": null, "channel": null },
  { "time": "16:37", "event": "login", "message": "", "user": "OmerCan", "new_nick": null, "email": "PAPATYAv7@7E.88.3D221A5B.sibertr.net", "channel": "#str_chat" },
  { "time": "16:37", "event": "chat", "message": "Selam dostlar, ne yapıyorsunuz?", "user": "OmerCan", "new_nick": null, "email": null, "channel": null },
  { "time": "16:37", "event": "chat", "message": "Hoş geldin OmerCan! Çok bir şey yok, muhabbet ediyoruz.", "user": "Boran", "new_nick": null, "email": null, "channel": null },
  { "time": "16:38", "event": "chat", "message": "Güzel güzel, ben de katılayım.", "user": "OmerCan", "new_nick": null, "email": null, "channel": null },
  { "time": "16:38", "event": "nick_change", "message": "", "user": "Eylul", "new_nick": "Eylul_99", "email": null, "channel": null },
  { "time": "16:39", "event": "chat", "message": "Aaa Eylül ismini değiştirdi :)", "user": "Zehra", "new_nick": null, "email": null, "channel": null },
  { "time": "16:39", "event": "chat", "message": "Evet ya, biraz değişiklik olsun dedim.", "user": "Eylul_99", "new_nick": null, "email": null, "channel": null },
  { "time": "16:40", "event": "quit", "message": "", "user": "Boran", "new_nick": null, "email": "PAPATYAv7@3A.8C.F7B22134.sibertr.net", "channel": null },
  { "time": "16:40", "event": "chat", "message": "Boran da gitti sanırım :)", "user": "OmerCan", "new_nick": null, "email": null, "channel": null },
  { "time": "16:41", "event": "chat", "message": "Evet, yine az kaldık.", "user": "Eylul_99", "new_nick": null, "email": null, "channel": null },
  { "time": "16:42", "event": "login", "message": "", "user": "Mert_", "new_nick": null, "email": "PAPATYAv7@4D.73.A6F5D122.sibertr.net", "channel": "#str_chat" },
  { "time": "16:42", "event": "chat", "message": "Selam millet, kaçırdığım bir şey var mı?", "user": "Mert_", "new_nick": null, "email": null, "channel": null },
  { "time": "18:20", "event": "login", "message": "", "user": "melis_", "new_nick": null, "email": "PAPATYAv7@6F.2D.9B7C1123.sibertr.net", "channel": "#str_chat" },
  { "time": "18:20", "event": "chat", "message": "slm kimler var?", "user": "melis_", "new_nick": null, "email": null, "channel": null },
  { "time": "18:21", "event": "chat", "message": "heeey melisss naber :))", "user": "irem34", "new_nick": null, "email": null, "channel": null },
  { "time": "18:21", "event": "chat", "message": "heyy iremm, iyiii iştee sennn??", "user": "melis_", "new_nick": null, "email": null, "channel": null },
  { "time": "18:22", "event": "chat", "message": "ayyyy napim ya iş güç işte klasik", "user": "irem34", "new_nick": null, "email": null, "channel": null },
  { "time": "18:22", "event": "chat", "message": "aynen ya, bende sabahtan beri ders çalışıyom kafam yandı sdfds", "user": "melis_", "new_nick": null, "email": null, "channel": null },
  { "time": "18:23", "event": "login", "message": "", "user": "nisa_98", "new_nick": null, "email": "PAPATYAv7@7E.88.3D221A5B.sibertr.net", "channel": "#str_chat" },
  { "time": "18:23", "event": "chat", "message": "selam kızlar ne anlatıyonuzz :p", "user": "nisa_98", "new_nick": null, "email": null, "channel": null },
  { "time": "18:24", "event": "chat", "message": "ayy nisaaa geldii :D", "user": "melis_", "new_nick": null, "email": null, "channel": null },
  { "time": "18:24", "event": "chat", "message": "günahımı anlatıyorum :P sdfgfdg", "user": "irem34", "new_nick": null, "email": null, "channel": null },
  { "time": "18:25", "event": "chat", "message": "yok yaa ben de çok sıkıldm napalım ya :(", "user": "nisa_98", "new_nick": null, "email": null, "channel": null },
  { "time": "18:25", "event": "chat", "message": "dizi önerin kankiler ben açıyım bari", "user": "nisa_98", "new_nick": null, "email": null, "channel": null },
  { "time": "18:26", "event": "chat", "message": "ay şu an netflixe bakan bi tek ben değilim dmi sdfgsdfg", "user": "melis_", "new_nick": null, "email": null, "channel": null },
  { "time": "18:26", "event": "chat", "message": "sjsjsjs aynen yaaa", "user": "irem34", "new_nick": null, "email": null, "channel": null },
  { "time": "18:27", "event": "quit", "message": "", "user": "irem34", "new_nick": null, "email": "PAPATYAv7@2B.6A.1E4D894A.sibertr.net", "channel": null },
  { "time": "18:27", "event": "chat", "message": "irem çıktı yaa kaldık başbaşa sdfsd", "user": "melis_", "new_nick": null, "email": null, "channel": null },
  { "time": "18:28", "event": "chat", "message": "napcaz kız kısır falan mı yoğurak sdfgdfg", "user": "nisa_98", "new_nick": null, "email": null, "channel": null },
  { "time": "18:29", "event": "login", "message": "", "user": "eda_", "new_nick": null, "email": "PAPATYAv7@5E.4D.8C56B7E3.sibertr.net", "channel": "#str_chat" },
  { "time": "18:29", "event": "chat", "message": "meraba bu oda aktif mi :D", "user": "eda_", "new_nick": null, "email": null, "channel": null },
  { "time": "18:29", "event": "chat", "message": "aktifiz şekerim hoşgeldin xd", "user": "melis_", "new_nick": null, "email": null, "channel": null },
  { "time": "18:30", "event": "chat", "message": "saol cnmm neler dönüyo :)", "user": "eda_", "new_nick": null, "email": null, "channel": null },
  { "time": "18:30", "event": "chat", "message": "dedikodu tabii ne olcak sdfgdfg", "user": "nisa_98", "new_nick": null, "email": null, "channel": null },
  { "time": "18:31", "event": "chat", "message": "ay canım yaa ben de biraz oturuyum burda", "user": "eda_", "new_nick": null, "email": null, "channel": null },
  { "time": "18:32", "event": "nick_change", "message": "", "user": "melis_", "new_nick": "meloshhh", "email": null, "channel": null },
  { "time": "18:32", "event": "chat", "message": "ayy bi değişiklik olsun dedim sdfsdg", "user": "meloshhh", "new_nick": null, "email": null, "channel": null },
  { "time": "18:33", "event": "quit", "message": "", "user": "nisa_98", "new_nick": null, "email": "PAPATYAv7@3A.8C.F7B22134.sibertr.net", "channel": null },
  { "time": "18:33", "event": "chat", "message": "yine eksildik ya sdfsd", "user": "eda_", "new_nick": null, "email": null, "channel": null },
  { "time": "18:34", "event": "chat", "message": "yok ya ben de kapatıcam azdan", "user": "meloshhh", "new_nick": null, "email": null, "channel": null },
  { "time": "18:35", "event": "quit", "message": "", "user": "meloshhh", "new_nick": null, "email": "PAPATYAv7@6F.2D.9B7C1123.sibertr.net", "channel": null },
  { "time": "18:36", "event": "chat", "message": "tek kaldım :)", "user": "eda_", "new_nick": null, "email": null, "channel": null },

]


export const nicknames = [
  { "nick": "bLueStar", "op": "~" },
  { "nick": "SiyahLeo", "op": "&" },
  { "nick": "NiGDe", "op": "&" },
  { "nick": "esmerim_23", "op": "&" },
  { "nick": "DuZCe", "op": "&" },
  { "nick": "Diablo", "op": "@" },
  { "nick": "CharGer", "op": "@" },
  { "nick": "Antik", "op": "@" },
  { "nick": "AseLina", "op": "@" },
  { "nick": "AsiPrens", "op": "@" },
  { "nick": "aXxxi", "op": "%" },
  { "nick": "ay_ca_", "op": "%" },
  { "nick": "aynur_", "op": "%" },
  { "nick": "AzRaiL", "op": "%" },
  { "nick": "Astsubay-Murat_", "op": "+" },
  { "nick": "Astsubay07", "op": "+" },
  { "nick": "Avukat_Akin", "op": "+" },
  { "nick": "AVUKAT_CEM06", "op": "+" },
  { "nick": "Avukat_Hakan", "op": "+" },
  { "nick": "Bahar001", "op": "" },
  { "nick": "bakkalamcan_M_", "op": "" },
  { "nick": "banderas34", "op": "" },
  { "nick": "barbiee", "op": "" },
  { "nick": "BARUT_", "op": "" },
  { "nick": "Batur", "op": "" },
  { "nick": "Bay_Seviyeli", "op": "" },
  { "nick": "BenDenizi", "op": "" },
  { "nick": "Beria", "op": "" },
  { "nick": "BERK33", "op": "" },
  { "nick": "berke_18", "op": "" },
  { "nick": "beste1213", "op": "" },
  { "nick": "beyciKo", "op": "" },
  { "nick": "billa", "op": "" },
  { "nick": "birisiA", "op": "" },
  { "nick": "BlehkD", "op": "" },
  { "nick": "bodrum_buse", "op": "" },
  { "nick": "BordoMavi61", "op": "" },
  { "nick": "BoşnakHakan", "op": "" },
  { "nick": "BRHM", "op": "" },
  { "nick": "brs42", "op": "" },
  { "nick": "Burak", "op": "" },
  { "nick": "Burhan1", "op": "" },
  { "nick": "Burhan1817", "op": "" },
  { "nick": "bursa_oguz44", "op": "" },
  { "nick": "busenur", "op": "" },
  { "nick": "byhard28", "op": "" },
  { "nick": "Börü", "op": "" },
  { "nick": "CafeiN", "op": "" },
  { "nick": "Cagkan_ist", "op": "" },
  { "nick": "canakkalemrkz", "op": "" },
  { "nick": "cemal_sahin", "op": "" },
  { "nick": "Ceren", "op": "" },
  { "nick": "CEYHUN_ist", "op": "" },
  { "nick": "Cha", "op": "" },
  { "nick": "Chesster34", "op": "" },
  { "nick": "ciddi_muhendis_TuRaB", "op": "" },
  { "nick": "Cinoo", "op": "" },
  { "nick": "ClubUser-459", "op": "" },
  { "nick": "CoLantiS", "op": "" },
  { "nick": "Dalton", "op": "" },
  { "nick": "DamLa", "op": "" },
  { "nick": "Deli_Seyyah", "op": "" },
  { "nick": "delifişek", "op": "" },
  { "nick": "deLy", "op": "" },
  { "nick": "demir_istan30", "op": "" },
  { "nick": "DesigneR", "op": "" },
  { "nick": "Dilan_ogrenci_konya", "op": "" },
  { "nick": "diyarbkr_", "op": "" },
  { "nick": "DOKTOR36_", "op": "" },
  { "nick": "dR_akdamara", "op": "" },
  { "nick": "DR_CIVAN", "op": "" },
  { "nick": "dr_ist34", "op": "" },
  { "nick": "DYRBAKIR30", "op": "" },
  { "nick": "EDNBULUR86", "op": "" },
  { "nick": "egemen_67", "op": "" },
  { "nick": "elitBirAdam", "op": "" },
  { "nick": "emir_34", "op": "" },
  { "nick": "emre_33", "op": "" },
  { "nick": "Emreee__", "op": "" },
  { "nick": "EniS", "op": "" },
  { "nick": "ERTUGRUList41", "op": "" },
  { "nick": "ethercity", "op": "" },
  { "nick": "Evet", "op": "" },
  { "nick": "Famiredo", "op": "" },
  { "nick": "FaRiD", "op": "" },
  { "nick": "Fearless", "op": "" },
  { "nick": "FirLama", "op": "" },
  { "nick": "Fundaa", "op": "" },
  { "nick": "gillidaran", "op": "" },
  { "nick": "Gizemm24", "op": "" },
  { "nick": "Godlessturtle", "op": "" },
  { "nick": "GoLBaSiLi", "op": "" },
  { "nick": "GoodGuy", "op": "" },
  { "nick": "Guest886145222", "op": "" },
  { "nick": "Huzurr", "op": "" }
];
