
export const bar = [
  { menu: 'File', submenu: ['New', 'Open', 'Save'] },
  { menu: 'View', submenu: ['Zoom In', 'Zoom Out'] },
  { menu: 'Favorites', submenu: ['Add to Favorites', 'View Favorites'] },
  { menu: 'Tools', submenu: ['Options', 'Settings'] },
  { menu: 'PAPATYA Script v7 e-mIRC', submenu: ['About', 'Help'] },
  { menu: 'Window', submenu: ['Minimize', 'Maximize'] },
  { menu: 'Help', submenu: ['Documentation', 'Support'] },
];

export const channels = ['istanbul', 'Kelime', 'KlasFM', 'Moos', 'Mynet_Sohbet', 'OXM', 'sohbet', 'TurkishChat'];

export const op_colors = [
  { sign: "~", color: "green" },
  { sign: "&", color: "#74140c" },
  { sign: "@", color: "#ea3323" },
  { sign: "%", color: "#00007a" },
  { sign: "+", color: "#0000f2" },
];

export const formatDate = (date: Date): string => {
  const days = [
    "Pazar", "Pazartesi", "Salı", "Çarşamba",
    "Perşembe", "Cuma", "Cumartesi"
  ];

  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = date.getFullYear();
  const dayName = days[date.getDay()];

  const hours = String(date.getHours()).padStart(2, "0");
  const minutes = String(date.getMinutes()).padStart(2, "0");
  const seconds = String(date.getSeconds()).padStart(2, "0");

  return `Tarih: ${day}/${month}/${year} ${dayName} - ${hours}:${minutes}:${seconds}`;
};

export const chats = [
  { "time": "02:07", "event": "chat", "message": "Bişeyi anlayamıyorum bile kafam hamura dönüyor", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:07", "event": "chat", "message": "Açmasan atar gider yapıyor", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:07", "event": "chat", "message": "Telefon", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:07", "event": "chat", "message": "Herşey çok çabuk eskitiliyor", "user": "Mina", "new_nick": null, "email": null, "channel": null },
  { "time": "02:08", "event": "chat", "message": "Çok çabuk değişiyor olaylar", "user": "Mina", "new_nick": null, "email": null, "channel": null },
  { "time": "02:08", "event": "quit", "message": "", "user": "ergin", "new_nick": null, "email": "MobilY@5E.79.3D55634C.sibertr.net", "channel": null },
  { "time": "02:08", "event": "nick_change", "message": "", "user": "Hazal", "new_nick": "Hazal' Away", "email": null, "channel": null },
  { "time": "02:08", "event": "chat", "message": "Maksatta bu belki", "user": "Mina", "new_nick": null, "email": null, "channel": null },
  { "time": "02:08", "event": "chat", "message": "Kafaların karışması", "user": "Mina", "new_nick": null, "email": null, "channel": null },
  { "time": "02:08", "event": "chat", "message": "Yazık ettiler bizim gibilerine senin gibilerine", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:08", "event": "login", "message": "", "user": "MobYaz-292", "new_nick": null, "email": "MobilY@5F.5A0E9A1C5.sibertr.net", "channel": "#Mynet_Sohbet" },
  { "time": "02:09", "event": "chat", "message": "Hiç durma aynı adamla telefon görüşmesi yapılır mı", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:09", "event": "chat", "message": "Nasıl :)))))", "user": "Mina", "new_nick": null, "email": null, "channel": null },
  { "time": "02:09", "event": "chat", "message": "Telefon rehberinde yaklaşık 400 tane adam var 1000 de 1000'i aynı adam aramakta", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:09", "event": "login", "message": "", "user": "sevde", "new_nick": null, "email": "MobilY@D9.52.952D5224.sibertr.net", "channel": "#Mynet_Sohbet" },
  { "time": "02:09", "event": "login", "message": "", "user": "aysunn", "new_nick": null, "email": "TurkishM@25.C9.8974D62C.sibertr.net", "channel": "#Mynet_Sohbet" },
  { "time": "02:09", "event": "chat", "message": "Misal verdim de yani", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:10", "event": "chat", "message": "Yaa :)", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:10", "event": "login", "message": "", "user": "MobYaz-439", "new_nick": null, "email": "MobilY@B0.DB.2F75F3CA.sibertr.net", "channel": "#Mynet_Sohbet" },
  { "time": "02:10", "event": "login", "message": "", "user": "Pokemon", "new_nick": null, "email": "MobilY@5.2E.21061F6E.sibertr.net", "channel": "#Mynet_Sohbet" },
  { "time": "02:10", "event": "chat", "message": "Anladım", "user": "Mina", "new_nick": null, "email": null, "channel": null },
  { "time": "02:10", "event": "quit", "message": "", "user": "Hazal' Away", "new_nick": null, "email": "MobilY@5.19.9B5EAEA4.sibertr.net", "channel": null },
  { "time": "02:10", "event": "chat", "message": "Bayan olsa da sesini duysan ama nerde duyamam", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:11", "event": "login", "message": "", "user": "Cokgec", "new_nick": null, "email": "MobilY@1F.8E.ECA2AA37.sibertr.net", "channel": "#Mynet_Sohbet" },
  { "time": "02:11", "event": "chat", "message": "Kafamızın içi yüzlerce topla dolu havada uçuşuyorlar", "user": "Mina", "new_nick": null, "email": null, "channel": null },
  { "time": "02:07", "event": "chat", "message": "Bişeyi anlayamıyorum bile kafam hamura dönüyor", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:07", "event": "chat", "message": "Açmasan atar gider yapıyor", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:07", "event": "chat", "message": "Telefon", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:07", "event": "chat", "message": "Herşey çok çabuk eskitiliyor", "user": "Mina", "new_nick": null, "email": null, "channel": null },
  { "time": "02:08", "event": "chat", "message": "Çok çabuk değişiyor olaylar", "user": "Mina", "new_nick": null, "email": null, "channel": null },
  { "time": "02:08", "event": "quit", "message": "", "user": "ergin", "new_nick": null, "email": "MobilY@5E.79.3D55634C.sibertr.net", "channel": null },
  { "time": "02:08", "event": "nick_change", "message": "", "user": "Hazal", "new_nick": "Hazal' Away", "email": null, "channel": null },
  { "time": "02:08", "event": "chat", "message": "Maksatta bu belki", "user": "Mina", "new_nick": null, "email": null, "channel": null },
  { "time": "02:08", "event": "chat", "message": "Kafaların karışması", "user": "Mina", "new_nick": null, "email": null, "channel": null },
  { "time": "02:08", "event": "chat", "message": "Yazık ettiler bizim gibilerine senin gibilerine", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:08", "event": "login", "message": "", "user": "MobYaz-292", "new_nick": null, "email": "MobilY@5F.5A0E9A1C5.sibertr.net", "channel": "#Mynet_Sohbet" },
  { "time": "02:09", "event": "chat", "message": "Hiç durma aynı adamla telefon görüşmesi yapılır mı", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:09", "event": "chat", "message": "Nasıl :)))))", "user": "Mina", "new_nick": null, "email": null, "channel": null },
  { "time": "02:09", "event": "chat", "message": "Telefon rehberinde yaklaşık 400 tane adam var 1000 de 1000'i aynı adam aramakta", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:09", "event": "login", "message": "", "user": "sevde", "new_nick": null, "email": "MobilY@D9.52.952D5224.sibertr.net", "channel": "#Mynet_Sohbet" },
  { "time": "02:09", "event": "login", "message": "", "user": "aysunn", "new_nick": null, "email": "TurkishM@25.C9.8974D62C.sibertr.net", "channel": "#Mynet_Sohbet" },
  { "time": "02:09", "event": "chat", "message": "Misal verdim de yani", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:10", "event": "chat", "message": "Yaa :)", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:10", "event": "login", "message": "", "user": "MobYaz-439", "new_nick": null, "email": "MobilY@B0.DB.2F75F3CA.sibertr.net", "channel": "#Mynet_Sohbet" },
  { "time": "02:10", "event": "login", "message": "", "user": "Pokemon", "new_nick": null, "email": "MobilY@5.2E.21061F6E.sibertr.net", "channel": "#Mynet_Sohbet" },
  { "time": "02:10", "event": "chat", "message": "Anladım", "user": "Mina", "new_nick": null, "email": null, "channel": null },
  { "time": "02:10", "event": "quit", "message": "", "user": "Hazal' Away", "new_nick": null, "email": "MobilY@5.19.9B5EAEA4.sibertr.net", "channel": null },
  { "time": "02:10", "event": "chat", "message": "Bayan olsa da sesini duysan ama nerde duyamam", "user": "Contura", "new_nick": null, "email": null, "channel": null },
  { "time": "02:11", "event": "login", "message": "", "user": "Cokgec", "new_nick": null, "email": "MobilY@1F.8E.ECA2AA37.sibertr.net", "channel": "#Mynet_Sohbet" },
  { "time": "02:11", "event": "chat", "message": "Kafamızın içi yüzlerce topla dolu havada uçuşuyorlar", "user": "Mina", "new_nick": null, "email": null, "channel": null },
]


export const nicknames = [
  { "nick": "bLueStar", "op": "~" },
  { "nick": "SiyahLeo", "op": "&" },
  { "nick": "NiGDe", "op": "&" },
  { "nick": "esmerim_23", "op": "&" },
  { "nick": "DuZCe", "op": "&" },
  { "nick": "Diablo", "op": "@" },
  { "nick": "CharGer", "op": "@" },
  { "nick": "Antik", "op": "@" },
  { "nick": "AseLina", "op": "@" },
  { "nick": "AsiPrens", "op": "@" },
  { "nick": "aXxxi", "op": "%" },
  { "nick": "ay_ca_", "op": "%" },
  { "nick": "aynur_", "op": "%" },
  { "nick": "AzRaiL", "op": "%" },
  { "nick": "Astsubay-Murat_", "op": "+" },
  { "nick": "Astsubay07", "op": "+" },
  { "nick": "Avukat_Akin", "op": "+" },
  { "nick": "AVUKAT_CEM06", "op": "+" },
  { "nick": "Avukat_Hakan", "op": "+" },
  { "nick": "Bahar001", "op": "" },
  { "nick": "bakkalamcan_M_", "op": "" },
  { "nick": "banderas34", "op": "" },
  { "nick": "barbiee", "op": "" },
  { "nick": "BARUT_", "op": "" },
  { "nick": "Batur", "op": "" },
  { "nick": "Bay_Seviyeli", "op": "" },
  { "nick": "BenDenizi", "op": "" },
  { "nick": "Beria", "op": "" },
  { "nick": "BERK33", "op": "" },
  { "nick": "berke_18", "op": "" },
  { "nick": "beste1213", "op": "" },
  { "nick": "beyciKo", "op": "" },
  { "nick": "billa", "op": "" },
  { "nick": "birisiA", "op": "" },
  { "nick": "BlehkD", "op": "" },
  { "nick": "bodrum_buse", "op": "" },
  { "nick": "BordoMavi61", "op": "" },
  { "nick": "BoşnakHakan", "op": "" },
  { "nick": "BRHM", "op": "" },
  { "nick": "brs42", "op": "" },
  { "nick": "Burak", "op": "" },
  { "nick": "Burhan1", "op": "" },
  { "nick": "Burhan1817", "op": "" },
  { "nick": "bursa_oguz44", "op": "" },
  { "nick": "busenur", "op": "" },
  { "nick": "byhard28", "op": "" },
  { "nick": "Börü", "op": "" },
  { "nick": "CafeiN", "op": "" },
  { "nick": "Cagkan_ist", "op": "" },
  { "nick": "canakkalemrkz", "op": "" },
  { "nick": "cemal_sahin", "op": "" },
  { "nick": "Ceren", "op": "" },
  { "nick": "CEYHUN_ist", "op": "" },
  { "nick": "Cha", "op": "" },
  { "nick": "Chesster34", "op": "" },
  { "nick": "ciddi_muhendis_TuRaB", "op": "" },
  { "nick": "Cinoo", "op": "" },
  { "nick": "ClubUser-459", "op": "" },
  { "nick": "CoLantiS", "op": "" },
  { "nick": "Dalton", "op": "" },
  { "nick": "DamLa", "op": "" },
  { "nick": "Deli_Seyyah", "op": "" },
  { "nick": "delifişek", "op": "" },
  { "nick": "deLy", "op": "" },
  { "nick": "demir_istan30", "op": "" },
  { "nick": "DesigneR", "op": "" },
  { "nick": "Dilan_ogrenci_konya", "op": "" },
  { "nick": "diyarbkr_", "op": "" },
  { "nick": "DOKTOR36_", "op": "" },
  { "nick": "dR_akdamara", "op": "" },
  { "nick": "DR_CIVAN", "op": "" },
  { "nick": "dr_ist34", "op": "" },
  { "nick": "DYRBAKIR30", "op": "" },
  { "nick": "EDNBULUR86", "op": "" },
  { "nick": "egemen_67", "op": "" },
  { "nick": "elitBirAdam", "op": "" },
  { "nick": "emir_34", "op": "" },
  { "nick": "emre_33", "op": "" },
  { "nick": "Emreee__", "op": "" },
  { "nick": "EniS", "op": "" },
  { "nick": "ERTUGRUList41", "op": "" },
  { "nick": "ethercity", "op": "" },
  { "nick": "Evet", "op": "" },
  { "nick": "Famiredo", "op": "" },
  { "nick": "FaRiD", "op": "" },
  { "nick": "Fearless", "op": "" },
  { "nick": "FirLama", "op": "" },
  { "nick": "Fundaa", "op": "" },
  { "nick": "gillidaran", "op": "" },
  { "nick": "Gizemm24", "op": "" },
  { "nick": "Godlessturtle", "op": "" },
  { "nick": "GoLBaSiLi", "op": "" },
  { "nick": "GoodGuy", "op": "" },
  { "nick": "Guest886145222", "op": "" },
  { "nick": "Huzurr", "op": "" }
];
